services:
  web:
    build: .
    volumes: &web-volumes
      - &app-volume .:/task_manager:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
      - &bundle-cache-volume bundle_cache:/bundle_cache
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
    depends_on:
      - db
    env_file:
      - .env
    command: bundle exec rails s -b '0.0.0.0' -p 3000

  db:
    image: postgres:11.4
    ports:
      - 5432:5432
    env_file:
      - .env

volumes:
  bundle_cache:
